# This formula is auto-generated by GoReleaser during releases.
# Manual install: brew tap themark007/knew && brew install knet
class Knet < Formula
  desc "Kubernetes network scanner: topology graphs, connectivity checks, AI analysis"
  homepage "https://github.com/themark007/knew"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/themark007/knew/releases/download/v#{version}/knet_#{version}_darwin_x86_64.tar.gz"
      sha256 "DARWIN_X86_64_SHA256_PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/themark007/knew/releases/download/v#{version}/knet_#{version}_darwin_arm64.tar.gz"
      sha256 "DARWIN_ARM64_SHA256_PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/themark007/knew/releases/download/v#{version}/knet_#{version}_linux_x86_64.tar.gz"
      sha256 "LINUX_X86_64_SHA256_PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/themark007/knew/releases/download/v#{version}/knet_#{version}_linux_arm64.tar.gz"
      sha256 "LINUX_ARM64_SHA256_PLACEHOLDER"
    end
  end

  def install
    bin.install "knet"
  end

  def post_install
    (var/"knet").mkpath
  end

  test do
    assert_match "knet version #{version}", shell_output("#{bin}/knet version")
  end
end
